spring:
  application:
    name:
      auth-microservice

  mail:
    username: test.modsen.software.newsletter@gmail.com
    password: "uikz ilhl jnft fpoh"
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/cab-agg}

  cloud:
    openfeign:
      client:
        config:
          keycloak-server:
            url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
          driver-microservice:
            url: ${DRIVER_SERVER_URL:http://localhost:8082/api/drivers}
          passenger-microservice:
            url: ${PASSENGER_SERVER_URL:http://localhost:8081/api/passengers}

keycloak:
  realm: ${KEYCLOAK_REALM:cab-agg}
  client-id-admin: ${KEYCLOAK_CLIENT_ID_ADMIN:admin-cli}
  client-id-user: ${KEYCLOAK_CLIENT_ID_USER:cab-auth}
  client-secret-user: ${KEYCLOAK_CLIENT_SECRET_USER:io6sADPUuG8RRgeo95ehblQe8rAgmzJG}
  admin-username: ${KC_BOOTSTRAP_ADMIN_USERNAME:admin}
  admin-password: ${KC_BOOTSTRAP_ADMIN_PASSWORD:admin}
  grant-type: ${KEYCLOAK_GRANT_TYPE:password}
  passenger-role-id: a2a3de93-e3bb-4344-9895-fad0f1404e2a
  driver-role-id: 6300c259-0a89-4798-bd6b-46542c6bb984
  admin-role-id: 3df1269d-637d-4f59-bc86-c92b965cdda7

server:
  port: 8085